name: build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: windows-latest
    steps:
      -
        name: Dump GitHub env
        run: |
          env
        shell: bash
      -
        name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
        shell: bash
      -
        name: Set TAG_NAME
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "##[set-env name=TAG_NAME;]${GITHUB_REF#refs/tags/}"
        shell: bash
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.4
      -
        name: Set GOPATH
        # temporary fix (see https://github.com/actions/setup-go/issues/14)
        run: |
          echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
          echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
        shell: bash
      -
        name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build
        env:
          REPO_URL: ${{ github.event.repository.url }}
        run: |
          go get -u github.com/kevinburke/go-bindata/go-bindata
          go get -u github.com/josephspurrier/goversioninfo/cmd/goversioninfo
          ant -noinput release
          ls -al bin/release/
        shell: bash
      -
        name: GitHub Release
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go get -u github.com/tcnksm/ghr
          ghr --version
          ghr -n ${TAG_NAME} -draft ${TAG_NAME} bin/release/
        shell: bash
